### ISSUE TITLE
Semantic-release

### ISSUE THREAD

**Issue by luanorlandi** [luanorlandi/gaming-bot-sdk#3]
Generate Changelog automatically and pipeline for releases. This should be linked somehow with commit messages and lint

https://github.com/semantic-release/changelog

**Comment by luanorlandi** [comment]
Pipeline should be something like this `.github/workflows/publish.yml` (the env var `NPM_AUTH_TOKEN` is already added in the repo):

```yml
name: CI
push:
  branches:
    - master
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run build
      - run: npm run lint
      - run: npm test
      - run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

```
